var rb = {
	mainTitle:				'AssetTracker RC 1.0',
	authWindowTitle:		'Authentication',
	authLabelUser:			'Username',
	authLabelPassword:		'Password',
	authLabelButton:		'Login',
	authInvalidTitle:		'Invalid Login!',
	authInvalidMessage:		'The username and/or password is invalid.',
	listTitle:				'Computers',
	systemNoteTitle:		'System Notes',
	systemNoteEditButton:	'Edit',
	saveNoteButton:			'Save Notes',
	removeMenu:				'Remove Application',
	removeAndChangeMenu:	'Remove Application & Record Change',
	reportButton:			'Reports',
	reportMenuAll:			'Full Computer Report',
	reportMenuProp:			'Computer Properties & Applications Report',
	reportMenuHistory:		'Computer Change History Report',
	reportUrl:				'./data/computerlog.cfm?type=computer&id=',	//System ID appended to this URL
	changeTitle:			'Change History',
	change:					'Change History',
	changeCategory:			'Type',
	changeDate:				'Date',
	changeLabel:			'Change',
	changeFormTitle:		'Create New Activity (Change Log)',
	changeUser:				'User',
	changeTypeTitle:		'Type',
	changeUserTitle:		'User',
	changeDateTitle:		'Date',
	changeEditTitle:		'Edit Change Log Entry',
	changeFieldUser:		'User',
	changeFieldAction:		'Activity/Change',
	changeFieldCategory:	'Category',
	changeFieldDate:		'Activity Date',
	changeSaveNewButton:	'Save New Change',
	changeResetButton:		'Reset Form',
	changeWarning:			'Only edit typos. New changes should have a new entry.',
	changeRemoveTitle:		'Remove Entry?',
	changeRemoveText:		'Removing change log entries is not advised. You should only remove duplicates or mis-entered entries. Are you sure you want to remove this entry?',
	propertyButton:			'Add Property',
	propertyButtonRemove:	'<i>Right click to remove a property.</i>',
	propertyWindowTitle:	'Create New System Property',
	propertyFieldName:		'Property Name',
	propertyFieldValue:		'Initial Value',
	propertyButtonSaveClose:'Save & Close',
	propertyButtonSaveNew:	'Save & Add Another',
	propertySaveWarning:	'<b>Unsaved changes will be lost!!!</b>',
	propertyUseAll:			'Use initial value as default for all computers.',
	propertyTitle:			'System Properties',
	removeProperty:			'Remove',
	removePropertyWarning:	'You are about to remove a property from the master list. This property will be removed from ALL systems and cannot be undone. Are you sure you wish to do this?',
	appAddButton:			'Add Application',
	appFieldName:			'Name',
	appFieldCategory:		'Category',
	appSaveButton:			'Save New Application',
	appRemoveInstruct:		'<i>Right click an application to remove.</i>',
	applicationsTitle:		'System Uses',
	appTitle:				'Application',
	appCategory:			'Category',
	appAddToChanges:		'Record to change history as installation.',
	appAddChangeTpl:		'Installed ',
	appAddDefaultCtg:		'Installation',
	appRmvChangeTpl:		'Uninstalled ',
	appRmvDefaultCtg:		'Uninstallation',
	opentabMenu:			'Edit Computer Properties',
	rdpurl:					'./data/rdp.cfm?comp=',	//Auto-appends the DNS name (i.e. computer.mydomain.local)
	sshurl:					'./data/ssh.cfm?comp=',	//Auto-appends the DNS name (i.e. computer.mydomain.local)
	data:					'./data/',
	rdp:					'Remote Desktop',
	ssh:					'SSH',
	reportNotFoundTitle:	'Report Not Found',
	reportNotFoundText:		'The report could not be found. This is caused by a system misconfiguration. Please contact your administrator or review the system documentation.',
	defaults: {
		loadmessage:		'Loading. Please wait....',
		savemessage:		'Save in progress. Please wait...',
		appCategory:		'Unknown'
	}
};

//Support extended resourcebundles
var xrb = {};